name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into server and run commands
      run: |
       sshpass -p '@lice_21109' ssh -p 20202 nallen@223.31.190.212 'touch /home/nallen/sample.txt'

