name: SSH Test

on:
  push:
    branches: [main] # Change this to match your branch

jobs:
  sshpass_test:
    runs-on: ubuntu-latest
    steps:
       - name: executing remote ssh commands using ssh key
         uses: appleboy/ssh-action@v1.0.3
         with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 20202
            script: whoami
